[package]
name = "telemetry"
version = "0.1.0"
authors = ["Parity Technologies Ltd. <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
actix = "0.8"
actix-web = "1.0.0"
actix-web-actors = "1.0.0"
bytes = "0.4"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
primitive-types = { version = "0.5.0", features = ["serde"] }
rustc-hash = "1.0.1"
log = "0.4"
simple_logger = "1.3.0"
num-traits = "0.2"
reqwest = "0.9.18"
